name: dsdsp-sync-github-$(Date:yyyyMMdd)

trigger:
  branches:
    include:
      - main

jobs:
- job: sync_to_github
  displayName: Sync to GitHub
  pool:
    vmImage: ubuntu-latest
  variables:
    - group: Azure-Static-Web-Apps-nice-rock-0193cc903-variable-group

  steps:
    - checkout: self
      submodules: true

    - script: |
        set -euo pipefail
        : "${GIT_PAT:?GIT_PAT is not set}"

        git config --global user.email "pipeline@azure.com"
        git config --global user.name "Azure Pipeline"

        git push "https://x-access-token:${GIT_PAT}@github.com/thomgiles/DSDSP.git" HEAD:main
      displayName: 'Sync to GitHub'
      env:
        GIT_PAT: $(GIT_PAT)