project:
  type: website

website:
  title: "Essential Digital Skills"
  navbar:
    left:
      - text: "EDS M1 (Web)"
        href: "EDS-M1.html"
      - text: "EDS M1 (Slides)"
        href: "EDS-M1.revealjs.html"