project:
  type: website
  output-dir: _site

website:
  title: "Data Science and Digital Skills Programme"
  navbar:
    left:
      - text: "Overview"
        href: "index.html"
      - text: "Essential Digital Skill"
        href: "esential_digital_skills/index.html"
  sidebar:
    style: "floating"
    contents:
      - section: "Learning modules"
        contents:
          - esential_digital_skills/index.qmd
          - esential_digital_skills/M1-digital_tools/index.qmd
          - esential_digital_skills/M2-data_governance_and_policy/index.qmd
          - esential_digital_skills/M3-something/index.qmd
          


