# Azure Pipelines for building and pushing EDS-Shiny Dash app image

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'eds-shiny-dashapp'

steps:
- task: Docker@2
  displayName: Build and push EDS-Shiny Docker image
  inputs:
    containerRegistry: 'DRSLinuxContainerRegistry-Docker'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: './helper_apps/EDS-Shiny/dockerfile'
    buildContext: './helper_apps/EDS-Shiny'
    tags: |
      $(Build.BuildId)
      latest
