project:
  type: website

website:
  title: "Essential Digital Skills"
  navbar:
    left:
      - text: "Digital Tools"
        href: "M1-digital_tools/index.html"
      - text: "Data Governance and Policy"
        href: "M2-data_governance_and_policy/index.html"