format:
  html:
    toc: true
    number-sections: false
    page-layout: article
  revealjs:
    theme: [black, ../../../uon.scss]
    slide-number: true
    chalkboard: true
    preview-links: auto
    logo: ./fig/logo.png
    footer: "Data Science and Digital Skills"
  pdf: 
    toc: True
