project:
  type: website
  output-dir: _site
  resources:
    - js/index-header-hero.js
    - js/index-workshop-rhythm.js
    - js/index-landing.js
    - js/about-header-hero.js
    - js/about-scroll-reveal.js
    - js/courses-header-hero.js
    - js/courses-finder.js
    - js/rjs-footer.js
    - html/reveal-header.html
  pre-render:
    - scripts/build_landing_data.py
  render:
    - "!_extensions/**"
    - "!.quarto/**"
    - "!.venv/**"
    - "!_freeze/**"
    - "!_site/**"
    - "!renv/**"
    - index.qmd
    - about.qmd
    - courses.qmd
    - courses/**/*.qmd

execute:
  freeze: auto

format:
  html:
    theme:
        - default
        - uon.scss
    toc: true
    number-sections: false
    page-layout: article

website:
  open-graph:
    locale: es_ES
    site-name: Quarto
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This site is currently under construction"
    type: primary
    position: below-navbar
    

  page-footer:
    left: |
      <h3>Location</h3>
      University of Nottingham  
      University Park  
      Nottingham, NG7 2RD  
      United Kingdom
    center: |
      <h3>Quick links</h3>
      [Submit an enquiry](mailto:digitalresearch@nottingham.ac.uk)  
      [Capabilities](#)  
      <a href="/about.html">About us</a>
      [Jobs](#)  
      [Privacy policy](#)
      
    right: |
     <h3>Get in touch</h3>
     <a href="mailto:digitalresearch@nottingham.ac.uk">digitalresearch@nottingham.ac.uk</a>
  
  navbar:
    title: ""
    logo: assets/UoN_logo.png
    collapse: true
    background: "#0e1a2b"
    foreground: "#ffffff"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Courses"
        href: courses.qmd

  sidebar:
    - id: "essential-digital-skills"
      title: "Essential Digital Skills"
      style: "docked"
      search: true
      collapse-level: 3
      contents:
        - text: "Overview"
          href: courses/essential_digital_skills/index.qmd
        - section: "Lessons"
          contents:
            - courses/essential_digital_skills/episodes/01-digital_tools.qmd
            - courses/essential_digital_skills/episodes/02-digital_delivery.qmd
            - courses/essential_digital_skills/episodes/03-data_governance_and_policy.qmd
            - courses/essential_digital_skills/episodes/04-research_data_managment.qmd
        - section: "Learners"
          contents:
            - courses/essential_digital_skills/learners/setup.qmd
            - courses/essential_digital_skills/learners/discuss.qmd
            - courses/essential_digital_skills/learners/reference.qmd
        - section: "Instructors"
          contents:
            - courses/essential_digital_skills/instructors/additional_material.qmd
            - courses/essential_digital_skills/instructors/extra_exercises.qmd
            - courses/essential_digital_skills/instructors/instructor-notes.qmd
        - section: "Community & Metadata"
          contents:
            - courses/essential_digital_skills/README.qmd
            - courses/essential_digital_skills/CONTRIBUTING.qmd
            - courses/essential_digital_skills/CODE_OF_CONDUCT.qmd
            - courses/essential_digital_skills/LICENSE.qmd
            - courses/essential_digital_skills/profiles/learner-profiles.qmd

    - id: "methods-for-data-science"
      title: "Methods for Data Science"
      style: "docked"
      search: true
      collapse-level: 3
      contents:
        - text: "Overview"
          href: courses/methods_for_data_science/index.qmd
        - section: "Lessons"
          contents:
            - courses/methods_for_data_science/episodes/05-collecting_the_right_data.qmd
            - courses/methods_for_data_science/episodes/06-organising_and_exploring_data.qmd
            - courses/methods_for_data_science/episodes/07-making_sense_of_data.qmd
            - courses/methods_for_data_science/episodes/08-insight_to_impacts.qmd
        - section: "Learners"
          contents:
            - courses/methods_for_data_science/learners/setup.qmd
            - courses/methods_for_data_science/learners/discuss.qmd
            - courses/methods_for_data_science/learners/reference.qmd
        - section: "Instructors"
          contents:
            - courses/methods_for_data_science/instructors/additional_material.qmd
            - courses/methods_for_data_science/instructors/extra_exercises.qmd
            - courses/methods_for_data_science/instructors/instructor-notes.qmd
        - section: "Community & Metadata"
          contents:
            - courses/methods_for_data_science/README.qmd
            - courses/methods_for_data_science/CONTRIBUTING.qmd
            - courses/methods_for_data_science/CODE_OF_CONDUCT.qmd
            - courses/methods_for_data_science/LICENSE.qmd
            - courses/methods_for_data_science/profiles/learner-profiles.qmd

    - id: "responsible-use-of-generative-ai"
      title: "Responsible Use of Generative AI"
      style: "docked"
      search: true
      collapse-level: 3
      contents:
        - text: "Overview"
          href: courses/responsible_use_of_generative_ai/index.qmd
        - section: "Lessons"
          contents:
            - courses/responsible_use_of_generative_ai/episodes/ext1-how_ai_impacts_research.qmd
            - courses/responsible_use_of_generative_ai/episodes/ext2-how_to_use_ai_in_research.qmd
        - section: "Learners"
          contents:
            - courses/responsible_use_of_generative_ai/learners/setup.qmd
            - courses/responsible_use_of_generative_ai/learners/discuss.qmd
            - courses/responsible_use_of_generative_ai/learners/reference.qmd
        - section: "Instructors"
          contents:
            - courses/responsible_use_of_generative_ai/instructors/additional_material.qmd
            - courses/responsible_use_of_generative_ai/instructors/extra_exercises.qmd
            - courses/responsible_use_of_generative_ai/instructors/instructor-notes.qmd
        - section: "Community & Metadata"
          contents:
            - courses/responsible_use_of_generative_ai/README.qmd
            - courses/responsible_use_of_generative_ai/CONTRIBUTING.qmd
            - courses/responsible_use_of_generative_ai/CODE_OF_CONDUCT.qmd
            - courses/responsible_use_of_generative_ai/LICENSE.qmd
            - courses/responsible_use_of_generative_ai/profiles/learner-profiles.qmd

    - id: "applied-python"
      title: "Applied Data Science (Python)"
      style: "docked"
      search: true
      collapse-level: 3
      contents:
        - text: "Overview"
          href: courses/applied_python/index.qmd
        - section: "Lessons"
          contents:
            - courses/applied_python/episodes/01-types_variables_and_basic_operations.qmd
            - courses/applied_python/episodes/02-loops_and_control_flow.qmd
            - courses/applied_python/episodes/03-data_manipulation_and_visualization.qmd
            - courses/applied_python/episodes/04_functions.qmd
            - courses/applied_python/episodes/05-data_manipulation_with_pandas.qmd
            - courses/applied_python/episodes/06-regression_analysis_and_modelling.qmd
            - courses/applied_python/episodes/07-python_object_oriented_programming.qmd
            - courses/applied_python/episodes/08-errors_debugging_and_defensive_programming.qmd
        - section: "Learners"
          contents:
            - courses/applied_python/learners/setup.qmd
            - courses/applied_python/learners/discuss.qmd
            - courses/applied_python/learners/reference.qmd
        - section: "Instructors"
          contents:
            - courses/applied_python/instructors/additional_material.qmd
            - courses/applied_python/instructors/extra_exercises.qmd
            - courses/applied_python/instructors/instructor-notes.qmd
        - section: "Community & Metadata"
          contents:
            - courses/applied_python/README.qmd
            - courses/applied_python/CONTRIBUTING.qmd
            - courses/applied_python/CODE_OF_CONDUCT.qmd
            - courses/applied_python/LICENSE.qmd
            - courses/applied_python/profiles/learner-profiles.qmd

    - id: "applied-r"
      title: "Applied Data Science (R)"
      style: "docked"
      search: true
      collapse-level: 3
      contents:
        - text: "Overview"
          href: courses/applied_R/index.qmd
        - section: "Lessons"
          contents:
            - courses/applied_R/episodes/01-Rstudio_intro.qmd
            - courses/applied_R/episodes/02-R_variables_intro.qmd
            - courses/applied_R/episodes/03-R_functions.qmd
            - courses/applied_R/episodes/04-for_loops.qmd
            - courses/applied_R/episodes/05-the_tidyverse.qmd
        - section: "Learners"
          contents:
            - courses/applied_R/learners/setup.qmd
            - courses/applied_R/learners/discuss.qmd
            - courses/applied_R/learners/reference.qmd
        - section: "Instructors"
          contents:
            - courses/applied_R/instructors/additional_material.qmd
            - courses/applied_R/instructors/extra_exercises.qmd
            - courses/applied_R/instructors/instructor-notes.qmd
        - section: "Community & Metadata"
          contents:
            - courses/applied_R/README.qmd
            - courses/applied_R/CONTRIBUTING.qmd
            - courses/applied_R/CODE_OF_CONDUCT.qmd
            - courses/applied_R/LICENSE.qmd
            - courses/applied_R/profiles/learner-profiles.qmd

    - id: "automating-business-processes"
      title: "Automating Business Processes"
      style: "docked"
      search: true
      collapse-level: 3
      contents:
        - text: "Overview"
          href: courses/automating_business_processes/index.qmd
        - section: "Lessons"
          contents:
            - courses/automating_business_processes/episodes/01-power_automate.qmd
        - section: "Learners"
          contents:
            - courses/automating_business_processes/learners/setup.qmd
            - courses/automating_business_processes/learners/additional_material.qmd
            - courses/automating_business_processes/learners/discuss.qmd
            - courses/automating_business_processes/learners/reference.qmd
        - section: "Instructors"
          contents:
            - courses/automating_business_processes/instructors/additional_material.qmd
            - courses/automating_business_processes/instructors/extra_exercises.qmd
            - courses/automating_business_processes/instructors/instructor-notes.qmd
        - section: "Community & Metadata"
          contents:
            - courses/automating_business_processes/README.qmd
            - courses/automating_business_processes/CONTRIBUTING.qmd
            - courses/automating_business_processes/CODE_OF_CONDUCT.qmd
            - courses/automating_business_processes/LICENSE.qmd
            - courses/automating_business_processes/profiles/learner-profiles.qmd
