project:
  type: website
  output-dir: _site

website:
  title: "Data Science and Digital Skills Programme"
  navbar:
    left:
      - text: "Overview"
        href: "index.html"
      - text: "Essential Digital Skill"
        href: "esential_digital_skills/index.html"

  sidebar:
    style: "floating"
    contents:
      - section: "Learning modules"
        contents:
          - section: "Esential Digital Skills"
            contents:
              - section: "Digital Research at UoN"
                contents:
                  - esential_digital_skills/digital_research_at_uon/episodes/01-digital_tools.qmd
                  - esential_digital_skills/digital_research_at_uon/episodes/02-digital_delivery.qmd
              - section: "Using Data Responsibly"
                contents:
                  - esential_digital_skills/using_data_responsibly/episodes/01-data_governance_and_policy.qmd
                  - esential_digital_skills/using_data_responsibly/episodes/02-research_data_managment.qmd
          - section: "Methods for Data Science"
            contents:
              - section: "Applied Data Sciences (Python)"
                contents:
                  - methods_for_data_science/python-novice-inflammation/episodes/01-intro.qmd
                  - methods_for_data_science/python-novice-inflammation/episodes/02-numpy.md
                  - methods_for_data_science/python-novice-inflammation/episodes/03-matplotlib.md
                  - methods_for_data_science/python-novice-inflammation/episodes/04-lists.md
                  - methods_for_data_science/python-novice-inflammation/episodes/05-loop.md
                  - methods_for_data_science/python-novice-inflammation/episodes/06-files.md
                  - methods_for_data_science/python-novice-inflammation/episodes/07-cond.md
                  - methods_for_data_science/python-novice-inflammation/episodes/08-func.md
                  - methods_for_data_science/python-novice-inflammation/episodes/09-errors.md
                  - methods_for_data_science/python-novice-inflammation/episodes/10-defensive.md
                  - methods_for_data_science/python-novice-inflammation/episodes/11-debugging.md
                  - methods_for_data_science/python-novice-inflammation/episodes/12-cmdline.md
