project:
  type: website
  output-dir: _site

execute:
  freeze: auto

format:
  html:
    theme:
        - default
        - uon.scss
    toc: true
    number-sections: false
    page-layout: article

website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  open-graph:
    locale: es_ES
    site-name: Quarto
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This site is currently under construction"
    type: primary
    position: below-navbar
    

  page-footer:
    left: |
      <h3>Location</h3>
      University of Nottingham  
      University Park  
      Nottingham, NG7 2RD  
      United Kingdom
    center: |
      <h3>Quick links</h3>
      [Submit an enquiry](#)  
      [Capabilities](#)  
      [About us](#)  
      [Jobs](#)  
      [Privacy policy](#)
      
    right: |
     <h3>Get in touch</h3>
     <a href="mailto:digitalresearch@nottingham.ac.uk">digitalresearch@nottingham.ac.uk</a>
  
  navbar:
    title: ""
    logo: assets/UoN_logo.png
    collapse: true
    background: "#0e1a2b"
    foreground: "#ffffff"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Essential Digital Skills"
        menu:
          - text: "Digital Tools"
            href: essential_digital_skills/episodes/01-digital_tools.qmd
          - text: "Digital Delivery"
            href: essential_digital_skills/episodes/02-digital_delivery.qmd
          - text: "Data Governance and Policy"
            href: essential_digital_skills/episodes/03-data_governance_and_policy.qmd
          - text: "Research Data Management"
            href: essential_digital_skills/episodes/04-research_data_managment.qmd
          - text: "Collecting the Right Data"
            href: essential_digital_skills/episodes/05-collecting_the_right_data.qmd
          - text: "Organising and Exploring Data"
            href: essential_digital_skills/episodes/06-organising_and_exploring_data.qmd
          - text: "Making Sense of Data"
            href: essential_digital_skills/episodes/07-making_sense_of_data.qmd
          - text: "Insight to Impact"
            href: essential_digital_skills/episodes/08-insight_to_impact.qmd
          - text: "Responsible AI"
            href: essential_digital_skills/episodes/ext1-responsible_ai.qmd
          - text: "Hands-on AI"
            href: essential_digital_skills/episodes/ext2-hands_on_ai.qmd


      - text: "Applied Data Science (Python)"
        menu:
          - text: "01 Intro"
            href: applied_python/episodes/01-intro.qmd
          - text: "02 Numpy"
            href: applied_python/episodes/02-numpy.qmd
          - text: "03 Matplotlib"
            href: applied_python/episodes/03-matplotlib.qmd
          - text: "04 Lists"
            href: applied_python/episodes/04-lists.qmd
          - text: "05 Loops"
            href: applied_python/episodes/05-loop.qmd
          - text: "06 Files"
            href: applied_python/episodes/06-files.qmd
          - text: "07 Conditionals"
            href: applied_python/episodes/07-cond.qmd
          - text: "08 Functions"
            href: applied_python/episodes/08-func.qmd
          - text: "09 Errors"
            href: applied_python/episodes/09-errors.qmd
          - text: "10 Defensive Programming"
            href: applied_python/episodes/10-defensive.qmd
          - text: "11 Debugging"
            href: applied_python/episodes/11-debugging.qmd
          - text: "12 Command Line"
            href: applied_python/episodes/12-cmdline.qmd

      - text: "Applied Data Science (R)"
        menu:
          - text: "01 RStudio Intro"
            href: applied_R/episodes/01-Rstudio_intro.qmd
          - text: "02 R Variables"
            href: applied_R/episodes/02-R_variables_intro.qmd
          - text: "03 R Functions"
            href: applied_R/episodes/03-R_functions.qmd
          - text: "04 For Loops"
            href: applied_R/episodes/04-for_loops.qmd
          - text: "05 The Tidyverse"
            href: applied_R/episodes/05-the_tidyverse.qmd



  sidebar:
    style: "docked"
    search: true
    collapse-level: 4
    contents:
      - section: "Learning modules"
        contents:
          - section: "Essential Digital Skills"
            href: essential_digital_skills/index.qmd
            contents:
              - essential_digital_skills/episodes/01-digital_tools.qmd
              - essential_digital_skills/episodes/02-digital_delivery.qmd
              - essential_digital_skills/episodes/03-data_governance_and_policy.qmd
              - essential_digital_skills/episodes/04-research_data_managment.qmd
              - essential_digital_skills/episodes/05-collecting_the_right_data.qmd
              - essential_digital_skills/episodes/06-organising_and_exploring_data.qmd
              - essential_digital_skills/episodes/07-making_sense_of_data.qmd
              - essential_digital_skills/episodes/08-insight_to_impact.qmd
              - essential_digital_skills/episodes/ext1-responsible_ai.qmd
              - essential_digital_skills/episodes/ext2-hands_on_ai.qmd

          - section: "Methods for Data Science"
            href: index.qmd
            contents:
              - section: "Applied Data Sciences (Python)"
                href: applied_python/index.qmd
                contents:
                  - section: "Episodes"
                    contents:
                      - applied_python/episodes/01-intro.qmd
                      - applied_python/episodes/02-numpy.qmd
                      - applied_python/episodes/03-matplotlib.md
                      - applied_python/episodes/04-lists.md
                      - applied_python/episodes/05-loop.md
                      - applied_python/episodes/06-files.md
                      - applied_python/episodes/07-cond.md
                      - applied_python/episodes/08-func.md
                      - applied_python/episodes/09-errors.md
                      - applied_python/episodes/10-defensive.md
                      - applied_python/episodes/11-debugging.md
                      - applied_python/episodes/12-cmdline.md
                  - section: "Learners"
                    contents:
                      - applied_python/learners/setup.md
                      - applied_python/learners/discuss.md
                      - applied_python/learners/reference.md
                  - section: "Instructors"
                    contents:
                      - applied_python/instructors/additional_material.md
                      - applied_python/instructors/extra_exercises.md
                      - applied_python/instructors/instructor-notes.md
                  - section: "Community & Metadata"
                    contents:
                      - applied_python/README.md
                      - applied_python/CONTRIBUTING.md
                      - applied_python/CODE_OF_CONDUCT.md
                      - applied_python/LICENSE.md
                      - applied_python/AUTHORS.md
                      - applied_python/profiles/learner-profiles.md

              - section: "Applied Data Sciences (R)"
                href: applied_R/index.md
                contents:
                  - section: "Episodes"
                    contents:
                      - applied_R/episodes/01-Rstudio_intro.qmd
                      - applied_R/episodes/02-R_variables_intro.qmd
                      - applied_R/episodes/03-R_functions.qmd
                      - applied_R/episodes/04-for_loops.qmd
                      - applied_R/episodes/05-the_tidyverse.qmd
                  - section: "Learners"
                    contents:
                      - applied_R/learners/setup.md
                      - applied_R/learners/discuss.md
                      - applied_R/learners/reference.md
                  - section: "Instructors"
                    contents:
                      - applied_R/instructors/instructor-notes.md
                  - section: "Community & Metadata"
                    contents:
                      - applied_R/README.md
                      - applied_R/CONTRIBUTING.md
                      - applied_R/CODE_OF_CONDUCT.md
                      - applied_R/LICENSE.md
                      - applied_R/profiles/learner-profiles.md


