project:
  type: default

format:
  revealjs:
    theme: default
    slide-number: true
    transition: fade
    chalkboard: true
    highlight-style: github
    preview-links: auto
    notes-server: true
