---
title: Setup
---

# Setup

This lesson is designed to be run on a personal computer.
All of the software and data used in this lesson are freely available online,
and instructions on how to obtain them are provided below.

## Install Python with Anaconda

We recommend using the Anaconda installer, which installs Python along with lots of packages which we will need in the lessons.

1. Open [https://www.anaconda.com/download](https://www.anaconda.com/download/success).
2. Download the Anaconda installer (if you are not sure which version to choose, you probably want the Graphical Installer).
3. Run the Anaconda Installer. Make sure to say yes to **Add Anaconda to my PATH environment variable**.

## Launch JupyterLab

This course will be taught using JupyterLab, a programming environment that runs in a web browser. After installing Anaconda, follow the instructions here to launch JupyterLab: [https://www.anaconda.com/docs/getting-started/guides/how-to-open-jupyterlab#](https://www.anaconda.com/docs/getting-started/guides/how-to-open-jupyterlab#).

## Obtain lesson materials

1. Download [python-novice-inflammation-data.zip](../episodes/data/python-novice-inflammation-data.zip)
  and [python-novice-inflammation-code.zip](../episodes/files/code/python-novice-inflammation-code.zip).
2. Create a folder called `swc-python` on your Desktop.
3. Move downloaded files to `swc-python`.
4. Unzip the files.

You should see two folders called `data` and `code` in the `swc-python` directory on your
Desktop.

::: {.callout-note}

Once you have successfully installed Anaconda, launched JupyterLab, and downloaded the lesson materials, your setup is complete.

:::

## Other Python environments

Although this course uses JupyterLab, there are other ways to run Python that you may want to explore, including:

- Python REPL: Open a command prompt or terminal and run `python` or `python3` or `py`, depending on your system.
- [Visual Studio Code](https://code.visualstudio.com/docs/python/)
- [PyCharm](https://www.jetbrains.com/pycharm/)
- [Spyder](https://www.spyder-ide.org)
- [IPython](https://ipython.org)
- [Google Colab](https://colab.research.google.com/)

